import React, { useState, useEffect, useCallback } from 'react';
import { Level, SoundType, SessionHistoryItem, CoachAnalysisPayload, CoachResponse, AILesson } from './types';
import { LESSONS, QUICK_DRILLS } from './data/lessons';
import { loadDailyStreak, recordDailyPractice, StreakData } from './utils/streak';
import { playKeySound } from './utils/sound';
import { Header } from './components/Header';
import { TypingArena } from './components/TypingArena';
import { VirtualKeyboard } from './components/VirtualKeyboard';
import { CoachModal } from './components/CoachModal';
import { AnalyticsModal } from './components/AnalyticsModal';
import { PrinciplesModal } from './components/PrinciplesModal';
import { AILessonBanner } from './components/AILessonBanner';
import { DailyGoalProgressRing } from './components/DailyGoalProgressRing';
import {
  Sparkles,
  BookOpen,
  ChevronRight,
  Flame,
  Award,
  Zap,
  Target,
  Maximize2,
  Minimize2,
  X,
} from 'lucide-react';

const STORAGE_KEY_HISTORY = 'ketikpro_history_v1';
const STORAGE_KEY_SOUND = 'ketikpro_sound_type';
const STORAGE_KEY_ZEN = 'ketikpro_zen_mode';
const STORAGE_KEY_VOLUME = 'ketikpro_volume_level';
const STORAGE_KEY_AI_LESSON = 'ketikpro_active_ai_lesson';
const STORAGE_KEY_DAILY_GOAL = 'ketikpro_daily_goal_wpm';

export default function App() {
  const [level, setLevel] = useState<Level>('pemula');
  const [lessonIndex, setLessonIndex] = useState<number>(0);
  const [customText, setCustomText] = useState<string | null>(null);
  const [soundType, setSoundType] = useState<SoundType>(() => {
    const saved = localStorage.getItem(STORAGE_KEY_SOUND) as SoundType;
    if (saved && ['linear', 'tactile', 'clicky', 'thock', 'muted'].includes(saved)) {
      return saved;
    }
    return 'linear';
  });
  const [volume, setVolume] = useState<number>(() => {
    const saved = localStorage.getItem(STORAGE_KEY_VOLUME);
    if (saved !== null) {
      const val = parseFloat(saved);
      if (!isNaN(val) && val >= 0 && val <= 1) {
        return val;
      }
    }
    return 0.5;
  });
  const [dailyGoal, setDailyGoal] = useState<number>(() => {
    const saved = localStorage.getItem(STORAGE_KEY_DAILY_GOAL);
    if (saved !== null) {
      const val = parseInt(saved, 10);
      if (!isNaN(val) && val >= 15 && val <= 200) {
        return val;
      }
    }
    return 40;
  });
  const [isFullscreen, setIsFullscreen] = useState<boolean>(false);
  const [showKeyboard, setShowKeyboard] = useState<boolean>(true);
  const [showHeatmap, setShowHeatmap] = useState<boolean>(true);
  const [isZenMode, setIsZenMode] = useState<boolean>(() => {
    return localStorage.getItem(STORAGE_KEY_ZEN) === 'true';
  });
  const [isSessionActive, setIsSessionActive] = useState<boolean>(false);
  const [streak, setStreak] = useState<StreakData>(() => loadDailyStreak());

  // Active AI Lesson generated by Coach
  const [activeAILesson, setActiveAILesson] = useState<AILesson | null>(() => {
    try {
      const saved = localStorage.getItem(STORAGE_KEY_AI_LESSON);
      return saved ? JSON.parse(saved) : null;
    } catch {
      return null;
    }
  });
  const [isRegeneratingAILesson, setIsRegeneratingAILesson] = useState<boolean>(false);

  // Keyboard active states
  const [currentExpectedChar, setCurrentExpectedChar] = useState<string>('');
  const [activePressedKey, setActivePressedKey] = useState<string | null>(null);
  const [activeWrongKey, setActiveWrongKey] = useState<string | null>(null);
  const [activeCorrectedKey, setActiveCorrectedKey] = useState<string | null>(null);

  // Modals & Coach States
  const [isCoachOpen, setIsCoachOpen] = useState<boolean>(false);
  const [isAnalyticsOpen, setIsAnalyticsOpen] = useState<boolean>(false);
  const [isPrinciplesOpen, setIsPrinciplesOpen] = useState<boolean>(false);

  const [coachResponse, setCoachResponse] = useState<CoachResponse | null>(null);
  const [isCoachLoading, setIsCoachLoading] = useState<boolean>(false);
  const [coachError, setCoachError] = useState<string | null>(null);
  const [lastPayload, setLastPayload] = useState<CoachAnalysisPayload | null>(null);

  // Session history
  const [history, setHistory] = useState<SessionHistoryItem[]>(() => {
    try {
      const saved = localStorage.getItem(STORAGE_KEY_HISTORY);
      return saved ? JSON.parse(saved) : [];
    } catch {
      return [];
    }
  });

  // Aggregate missed key frequencies from all session history
  const missedKeyFrequencies = React.useMemo(() => {
    const freqs: Record<string, number> = {};
    history.forEach((sess) => {
      if (sess.missed_keys_counts) {
        Object.entries(sess.missed_keys_counts).forEach(([k, cnt]) => {
          const lower = k.toLowerCase();
          freqs[lower] = (freqs[lower] || 0) + cnt;
        });
      } else if (sess.weak_keys) {
        sess.weak_keys.forEach((k) => {
          const lower = k.toLowerCase();
          freqs[lower] = (freqs[lower] || 0) + 1;
        });
      }
    });
    return freqs;
  }, [history]);

  // Current target text calculation
  const currentLessons = LESSONS[level] || LESSONS.pemula;
  const currentLesson = currentLessons[lessonIndex] || currentLessons[0];
  const targetText = customText || currentLesson.text;

  // Save history to localStorage
  const saveSessionToHistory = (item: SessionHistoryItem) => {
    setHistory((prev) => {
      const updated = [...prev, item];
      try {
        localStorage.setItem(STORAGE_KEY_HISTORY, JSON.stringify(updated.slice(-50)));
      } catch (e) {
        console.error('Failed to save history', e);
      }
      return updated;
    });
  };

  // Fullscreen state listener
  useEffect(() => {
    const handleFsChange = () => {
      setIsFullscreen(Boolean(document.fullscreenElement));
    };
    document.addEventListener('fullscreenchange', handleFsChange);
    return () => document.removeEventListener('fullscreenchange', handleFsChange);
  }, []);

  const handleToggleFullscreen = () => {
    if (!document.fullscreenElement) {
      document.documentElement.requestFullscreen().catch(() => {});
    } else {
      document.exitFullscreen().catch(() => {});
    }
  };

  // Keyboard shortcut to toggle Zen Mode (Alt+Z)
  useEffect(() => {
    const handleZenShortcut = (e: KeyboardEvent) => {
      if (e.altKey && e.key.toLowerCase() === 'z') {
        e.preventDefault();
        handleToggleZenMode();
      }
    };
    window.addEventListener('keydown', handleZenShortcut);
    return () => window.removeEventListener('keydown', handleZenShortcut);
  }, []);

  // Today's practice stats for Daily Goal tracking
  const todayStats = React.useMemo(() => {
    const today = new Date();
    const todaySessions = history.filter((item) => {
      const timestamp = parseInt(item.id, 10);
      if (!isNaN(timestamp)) {
        const d = new Date(timestamp);
        return (
          d.getFullYear() === today.getFullYear() &&
          d.getMonth() === today.getMonth() &&
          d.getDate() === today.getDate()
        );
      }
      return false;
    });

    const bestWpmToday = todaySessions.length > 0 ? Math.max(...todaySessions.map((s) => s.wpm)) : 0;
    return {
      todaySessions,
      count: todaySessions.length,
      bestWpmToday,
    };
  }, [history]);

  const handleUpdateDailyGoal = (newGoal: number) => {
    setDailyGoal(newGoal);
    localStorage.setItem(STORAGE_KEY_DAILY_GOAL, newGoal.toString());
  };

  const handleSoundChange = (newSound: SoundType) => {
    setSoundType(newSound);
    localStorage.setItem(STORAGE_KEY_SOUND, newSound);
  };

  const handleVolumeChange = (newVol: number) => {
    const clamped = Math.max(0, Math.min(1, newVol));
    setVolume(clamped);
    localStorage.setItem(STORAGE_KEY_VOLUME, String(clamped));
    if (soundType !== 'muted' && clamped > 0) {
      playKeySound(soundType, clamped);
    }
  };

  const handleToggleZenMode = () => {
    setIsZenMode((prev) => {
      const next = !prev;
      localStorage.setItem(STORAGE_KEY_ZEN, String(next));
      return next;
    });
  };

  const handleSelectLevel = (newLevel: Level) => {
    setLevel(newLevel);
    setLessonIndex(0);
    setCustomText(null);
  };

  // Call KetikPro Coach API
  const requestCoachAnalysis = useCallback(async (payload: CoachAnalysisPayload) => {
    setLastPayload(payload);
    setIsCoachOpen(true);
    setIsCoachLoading(true);
    setCoachError(null);

    try {
      const response = await fetch('/api/coach', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(payload),
      });

      if (!response.ok) {
        throw new Error(`Server status: ${response.status}`);
      }

      const data: CoachResponse = await response.json();
      setCoachResponse(data);
      if (data.ai_lesson) {
        setActiveAILesson(data.ai_lesson);
        try {
          localStorage.setItem(STORAGE_KEY_AI_LESSON, JSON.stringify(data.ai_lesson));
        } catch (e) {
          console.error('Failed to save AI lesson', e);
        }
      }
    } catch (err) {
      console.error('Coach request failed:', err);
      setCoachError('Gagal memuat analisis dari KetikPro Coach. Coba lagi beberapa saat lagi.');
    } finally {
      setIsCoachLoading(false);
    }
  }, []);

  // When a practice session completes
  const handleSessionComplete = (payload: CoachAnalysisPayload) => {
    // Count errors per expected character
    const errorMap: Record<string, number> = {};
    payload.errors.forEach((err) => {
      const key = (err.expected || '').toLowerCase();
      if (key) {
        errorMap[key] = (errorMap[key] || 0) + 1;
      }
    });

    const historyItem: SessionHistoryItem = {
      id: `${Date.now()}`,
      date: new Date().toLocaleDateString('id-ID', {
        month: 'short',
        day: 'numeric',
        hour: '2-digit',
        minute: '2-digit',
      }),
      wpm: payload.wpm,
      accuracy: payload.accuracy,
      raw_accuracy: payload.raw_accuracy,
      corrected_count: payload.corrected_errors_count,
      uncorrected_count: payload.uncorrected_errors_count,
      level: payload.level,
      duration_seconds: payload.duration_seconds,
      weak_keys: payload.errors.map((e) => e.expected).slice(0, 3),
      missed_keys_counts: errorMap,
    };
    saveSessionToHistory(historyItem);

    // Update Daily Streak counter in localStorage
    const updatedStreak = recordDailyPractice();
    setStreak(updatedStreak);

    // Call coach analysis automatically
    requestCoachAnalysis(payload);
  };

  // User applies drill or AI Lesson generated by KetikPro Coach
  const handleApplyNextDrill = (drillText: string, aiLesson?: AILesson) => {
    setCustomText(drillText);
    if (aiLesson) {
      setActiveAILesson(aiLesson);
      try {
        localStorage.setItem(STORAGE_KEY_AI_LESSON, JSON.stringify(aiLesson));
      } catch (e) {
        console.error('Failed to save AI lesson', e);
      }
    }
  };

  // Regenerate standalone AI lesson on demand
  const handleRegenerateAILesson = async () => {
    setIsRegeneratingAILesson(true);
    try {
      const weakKeysSet = new Set<string>();
      history.slice(-5).forEach((h) => {
        (h.weak_keys || []).forEach((k) => weakKeysSet.add(k));
      });
      const recentWpm = history.length > 0 ? history[history.length - 1].wpm : 30;

      const res = await fetch('/api/ai-lesson', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          level,
          focus_keys: Array.from(weakKeysSet).slice(0, 4),
          recent_wpm: recentWpm,
        }),
      });

      if (res.ok) {
        const data: AILesson = await res.json();
        setActiveAILesson(data);
        setCustomText(data.teks_lesson);
        try {
          localStorage.setItem(STORAGE_KEY_AI_LESSON, JSON.stringify(data));
        } catch (e) {
          console.error(e);
        }
      }
    } catch (err) {
      console.error('Failed to regenerate AI lesson:', err);
    } finally {
      setIsRegeneratingAILesson(false);
    }
  };

  const handleReset = () => {
    // Re-trigger current text
    const cur = targetText;
    setCustomText('');
    setTimeout(() => {
      setCustomText(cur);
    }, 10);
  };

  return (
    <div className="min-h-screen bg-slate-950 text-slate-100 flex flex-col font-sans transition-all duration-300">
      {/* If Zen Mode is active, render the dedicated Single-Screen Focus Layout */}
      {isZenMode ? (
        <div className="fixed inset-0 z-50 bg-slate-950 flex flex-col justify-between p-3 sm:p-5 overflow-hidden select-none animate-in fade-in duration-200">
          {/* Zen Minimal Header */}
          <div className="w-full max-w-4xl mx-auto flex items-center justify-between pb-2 border-b border-slate-900 text-xs">
            <div className="flex items-center gap-2">
              <span className="flex items-center gap-1.5 px-2.5 py-1 rounded-full bg-blue-500/10 text-blue-400 border border-blue-500/20 font-bold text-[11px]">
                <span className="w-2 h-2 rounded-full bg-blue-400 animate-pulse" />
                Zen Mode • Layar Tunggal
              </span>
              <span className="text-slate-400 hidden sm:inline truncate max-w-xs font-medium">
                {activeAILesson && customText === activeAILesson.teks_lesson ? activeAILesson.judul : currentLesson.title}
              </span>
            </div>

            <div className="flex items-center gap-2">
              {/* Daily Goal badge in Zen Top Bar */}
              <div className="flex items-center gap-1.5 px-2.5 py-1 rounded-xl bg-slate-900 border border-slate-800 text-[11px] text-slate-300">
                <Target className="w-3.5 h-3.5 text-emerald-400" />
                <span>Target: <strong className="font-mono text-slate-100">{dailyGoal} WPM</strong></span>
              </div>

              {/* Fullscreen Toggle */}
              <button
                onClick={handleToggleFullscreen}
                className="p-1.5 rounded-xl bg-slate-900 hover:bg-slate-800 text-slate-400 hover:text-white border border-slate-800 transition"
                title={isFullscreen ? 'Keluar Layar Penuh' : 'Layar Penuh'}
              >
                {isFullscreen ? <Minimize2 className="w-4 h-4" /> : <Maximize2 className="w-4 h-4" />}
              </button>

              {/* Exit Zen Button */}
              <button
                onClick={handleToggleZenMode}
                className="flex items-center gap-1.5 px-3 py-1 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-200 text-xs font-semibold transition border border-slate-700 active:scale-95"
                title="Keluar dari Zen Mode (Alt+Z)"
              >
                <X className="w-3.5 h-3.5" />
                <span>Keluar Zen</span>
              </button>
            </div>
          </div>

          {/* Centered Typing Arena in Zen Mode */}
          <div className="flex-1 flex flex-col justify-center w-full max-w-4xl mx-auto my-auto min-h-0 py-2">
            <TypingArena
              level={level}
              targetText={targetText}
              soundType={soundType}
              volume={volume}
              onSessionComplete={handleSessionComplete}
              onReset={handleReset}
              onRequestCoachAnalysis={requestCoachAnalysis}
              onActiveCharChange={setCurrentExpectedChar}
              onKeyActivity={setActivePressedKey}
              onWrongKeyActivity={setActiveWrongKey}
              onCorrectedKeyActivity={setActiveCorrectedKey}
              onSessionActiveChange={setIsSessionActive}
              history={history}
              isZenMode={true}
            />
          </div>

          {/* Bottom Virtual Keyboard in Zen Mode - pinned neatly to fit single screen */}
          <div className="w-full max-w-4xl mx-auto flex-shrink-0 pt-1">
            <VirtualKeyboard
              currentExpectedChar={currentExpectedChar}
              activePressedKey={activePressedKey}
              activeWrongKey={activeWrongKey}
              activeCorrectedKey={activeCorrectedKey}
              showFingerGuides={true}
              missedKeyFrequencies={missedKeyFrequencies}
              showHeatmap={showHeatmap}
              onToggleHeatmap={() => setShowHeatmap(!showHeatmap)}
              isCompact={true}
            />
          </div>
        </div>
      ) : (
        <>
          {/* Top Navigation */}
          <div>
            <Header
              currentLevel={level}
              onSelectLevel={handleSelectLevel}
              isCustomDrill={Boolean(customText)}
              soundType={soundType}
              onChangeSoundType={handleSoundChange}
              volume={volume}
              onChangeVolume={handleVolumeChange}
              showKeyboard={showKeyboard}
              onToggleKeyboard={() => setShowKeyboard(!showKeyboard)}
              onOpenAnalytics={() => setIsAnalyticsOpen(true)}
              onOpenPrinciples={() => setIsPrinciplesOpen(true)}
              isZenMode={isZenMode}
              onToggleZenMode={handleToggleZenMode}
              streak={streak}
              dailyGoal={dailyGoal}
              onUpdateDailyGoal={handleUpdateDailyGoal}
              bestWpmToday={todayStats.bestWpmToday}
            />
          </div>

          {/* Main Container */}
          <main className="flex-1 max-w-5xl w-full mx-auto px-4 py-6 flex flex-col items-center gap-6 transition-all duration-300">
            {/* Lesson Navigation Header */}
            <div className="w-full flex flex-wrap items-center justify-between gap-3 pb-2 border-b border-slate-800/80">
              <div className="flex items-center gap-2">
                <div className={`p-1.5 rounded-lg ${
                  activeAILesson && customText === activeAILesson.teks_lesson
                    ? 'bg-indigo-500/20 text-indigo-400'
                    : 'bg-blue-500/10 text-blue-400'
                }`}>
                  {activeAILesson && customText === activeAILesson.teks_lesson ? (
                    <Sparkles className="w-4 h-4 animate-pulse" />
                  ) : (
                    <BookOpen className="w-4 h-4" />
                  )}
                </div>
                <div>
                  <div className="flex items-center gap-2">
                    <span className={`text-xs font-bold uppercase tracking-wider ${
                      activeAILesson && customText === activeAILesson.teks_lesson
                        ? 'text-indigo-400'
                        : 'text-blue-400'
                    }`}>
                      {activeAILesson && customText === activeAILesson.teks_lesson
                        ? 'Materi Khusus AI Guide'
                        : customText
                        ? 'Latihan Tuts Khusus Coach'
                        : `Level ${level.toUpperCase()}`}
                    </span>
                    {!customText && (
                      <span className="text-xs text-slate-500">
                        • Latihan {lessonIndex + 1} dari {currentLessons.length}
                      </span>
                    )}
                  </div>
                  <h2 className="text-base font-bold text-slate-200">
                    {activeAILesson && customText === activeAILesson.teks_lesson
                      ? activeAILesson.judul
                      : customText
                      ? 'Drill Tuts Rekomendasi Coach'
                      : currentLesson.title}
                  </h2>
                </div>
              </div>

              {/* Quick Lesson Switcher */}
              <div className="flex items-center gap-1.5 overflow-x-auto max-w-full py-1">
                {/* Standard Curriculum Lessons */}
                {!customText && currentLessons.map((les, idx) => (
                  <button
                    key={les.id}
                    onClick={() => {
                      setLessonIndex(idx);
                      setCustomText(null);
                    }}
                    className={`px-3 py-1 rounded-xl text-xs font-semibold whitespace-nowrap transition ${
                      lessonIndex === idx
                        ? 'bg-blue-600 text-white font-bold border border-blue-400/50 shadow-sm shadow-blue-600/30'
                        : 'bg-slate-900/60 text-slate-400 hover:text-slate-200 border border-slate-800'
                    }`}
                  >
                    {idx + 1}. {les.title}
                  </button>
                ))}

                {/* AI Lesson Quick Toggle Button */}
                <button
                  onClick={() => {
                    if (activeAILesson) {
                      setCustomText(activeAILesson.teks_lesson);
                    } else {
                      handleRegenerateAILesson();
                    }
                  }}
                  disabled={isRegeneratingAILesson}
                  className={`px-3 py-1 rounded-xl text-xs font-semibold whitespace-nowrap transition flex items-center gap-1.5 ${
                    activeAILesson && customText === activeAILesson.teks_lesson
                      ? 'bg-gradient-to-r from-indigo-600 to-blue-600 text-white font-bold border border-indigo-400/50 shadow-sm shadow-indigo-600/30'
                      : 'bg-indigo-950/60 text-indigo-300 hover:text-white border border-indigo-500/30'
                  }`}
                  title={activeAILesson ? `Buka Lesson AI: ${activeAILesson.judul}` : 'Minta AI merancang teks materi lesson khusus untukmu'}
                >
                  <Sparkles className={`w-3 h-3 ${isRegeneratingAILesson ? 'animate-spin text-amber-400' : 'text-indigo-400'}`} />
                  <span>{isRegeneratingAILesson ? 'Menyusun...' : 'Lesson AI'}</span>
                </button>

                {customText && (
                  <button
                    onClick={() => setCustomText(null)}
                    className="text-xs text-blue-400 hover:text-blue-300 underline font-medium ml-2 whitespace-nowrap"
                  >
                    Kembali ke materi level
                  </button>
                )}
              </div>
            </div>

            {/* AI Lesson Guide Banner (Visible when AI Lesson is active) */}
            {activeAILesson && customText === activeAILesson.teks_lesson && (
              <AILessonBanner
                aiLesson={activeAILesson}
                onRegenerate={handleRegenerateAILesson}
                isRegenerating={isRegeneratingAILesson}
                onExitAILesson={() => setCustomText(null)}
              />
            )}

            {/* Typing Arena (Real-time speed, accuracy, text box) */}
            <TypingArena
              level={level}
              targetText={targetText}
              soundType={soundType}
              volume={volume}
              onSessionComplete={handleSessionComplete}
              onReset={handleReset}
              onRequestCoachAnalysis={requestCoachAnalysis}
              onActiveCharChange={setCurrentExpectedChar}
              onKeyActivity={setActivePressedKey}
              onWrongKeyActivity={setActiveWrongKey}
              onCorrectedKeyActivity={setActiveCorrectedKey}
              onSessionActiveChange={setIsSessionActive}
              history={history}
            />

            {/* Virtual Keyboard (Visual 10-Finger guide & Heatmap Overlay) */}
            {showKeyboard && (
              <div className="w-full mt-2 animate-in fade-in duration-300">
                <VirtualKeyboard
                  currentExpectedChar={currentExpectedChar}
                  activePressedKey={activePressedKey}
                  activeWrongKey={activeWrongKey}
                  activeCorrectedKey={activeCorrectedKey}
                  showFingerGuides={true}
                  missedKeyFrequencies={missedKeyFrequencies}
                  showHeatmap={showHeatmap}
                  onToggleHeatmap={() => setShowHeatmap(!showHeatmap)}
                />
              </div>
            )}

            {/* Quick Drill Presets Bar */}
            <div className="w-full max-w-4xl p-4 rounded-2xl bg-slate-900/60 border border-slate-800/80 flex flex-wrap items-center justify-between gap-3">
              <div className="flex items-center gap-2 text-xs text-slate-400 font-medium">
                <Flame className="w-4 h-4 text-blue-400" />
                <span>Pilihan Latihan Kilat:</span>
              </div>

              <div className="flex flex-wrap items-center gap-2">
                {QUICK_DRILLS.map((drill, dIdx) => (
                  <button
                    key={dIdx}
                    onClick={() => setCustomText(drill.text)}
                    className="px-2.5 py-1 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-300 hover:text-white text-xs border border-slate-700/80 transition"
                  >
                    {drill.name}
                  </button>
                ))}
              </div>
            </div>
          </main>

          {/* Footer info bar with Daily Goal Progress Ring */}
          <footer className="w-full border-t border-slate-900 py-4 bg-slate-950/80 text-xs text-slate-500">
            <div className="max-w-5xl mx-auto px-4 flex flex-wrap items-center justify-between gap-4">
              {/* Daily Goal Progress Ring */}
              <DailyGoalProgressRing
                dailyGoal={dailyGoal}
                bestWpmToday={todayStats.bestWpmToday}
                todaySessionCount={todayStats.count}
                onClick={() => setIsAnalyticsOpen(true)}
              />

              <div className="flex items-center gap-4">
                <button
                  onClick={() => setIsPrinciplesOpen(true)}
                  className="hover:text-slate-300 transition"
                >
                  Prinsip 10 Jari
                </button>
                <button
                  onClick={() => setIsAnalyticsOpen(true)}
                  className="hover:text-slate-300 transition"
                >
                  Statistik Sesi
                </button>
                <span className="hidden sm:inline text-slate-600">|</span>
                <span className="hidden sm:inline text-slate-400">
                  KetikPro Coach — Pelatih Mengetik 10 Jari Cerdas
                </span>
              </div>
            </div>
          </footer>
        </>
      )}

      {/* Coach Analysis Modal */}
      <CoachModal
        isOpen={isCoachOpen}
        onClose={() => setIsCoachOpen(false)}
        coachResponse={coachResponse}
        isLoading={isCoachLoading}
        error={coachError}
        sessionPayload={lastPayload}
        onApplyNextDrill={handleApplyNextDrill}
        onRetryCurrent={handleReset}
        streak={streak}
      />

      {/* Analytics Modal */}
      <AnalyticsModal
        isOpen={isAnalyticsOpen}
        onClose={() => setIsAnalyticsOpen(false)}
        history={history}
        onClearHistory={() => {
          setHistory([]);
          localStorage.removeItem(STORAGE_KEY_HISTORY);
        }}
        streak={streak}
      />

      {/* Principles & Ergonomics Modal */}
      <PrinciplesModal
        isOpen={isPrinciplesOpen}
        onClose={() => setIsPrinciplesOpen(false)}
      />
    </div>
  );
}
